Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,12 @@
 #!/usr/bin/env bash
+
+indent() {
+    sed -u 's/^/      /'
+}
+
+echo "Copied ${PROCFILE} as Procfile successfully" | indent
+
+
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
 # fail fast
@@ -10,6 +18,20 @@ BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
+
+PROCFILE=$(cat ${ENV_DIR}/PROCFILE)
+
+if [[ -z "${PROCFILE}" ]]; then
+    echo "PROCFILE was not set. Aborting" | indent
+    exit 1
+fi
+
+cp ${BUILD_DIR}/${PROCFILE} ${BUILD_DIR}/Procfile
+
+if ! [ $? ]; then
+    echo "FAILED to copy a Procfile" | indent
+    exit 1
+fi
 
 source $BP_DIR/lib/common.sh
 source $BP_DIR/lib/maven.sh
